# Generated by Django 4.1 on 2025-11-10 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True, related_name="shared_meals", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
